# Generated by Django 4.1 on 2024-10-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='movie_image',
        ),
    ]
